language: python
sudo: false
cache: pip
python:
  - '3.5'
  - '3.4'
  - '2.7'
env:
  - REQ='Django>=1.10,<1.11'
  - REQ='Django>=1.11,<2.0'
  - REQ='https://github.com/django/django/archive/master.zip#egg=Django'
matrix:
  allow_failures:
    - env: REQ='https://github.com/django/django/archive/master.zip#egg=Django'
  exclude:
    - python: '2.7'
      env: REQ='https://github.com/django/django/archive/master.zip#egg=Django'
install:
  - pip install -U pip wheel
  - pip install $REQ flake8
  - python setup.py install
script: 'cd tests && ./manage.py test testapp && cd .. && flake8 .'
